// <auto-generated />
using CMDB.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CMDB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CMDB.Models.ConfigurationItem", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Responsible");

                    b.Property<string>("Version");

                    b.HasKey("Name");

                    b.ToTable("ConfigurationItems");
                });

            modelBuilder.Entity("CMDB.Models.Dependency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BaseCIName");

                    b.Property<string>("DependencyCIName");

                    b.HasKey("Id");

                    b.HasIndex("BaseCIName");

                    b.HasIndex("DependencyCIName");

                    b.ToTable("Dependencies");
                });

            modelBuilder.Entity("CMDB.Models.Dependency", b =>
                {
                    b.HasOne("CMDB.Models.ConfigurationItem", "BaseCI")
                        .WithMany("BaseItems")
                        .HasForeignKey("BaseCIName");

                    b.HasOne("CMDB.Models.ConfigurationItem", "DependencyCI")
                        .WithMany("DependencyItems")
                        .HasForeignKey("DependencyCIName");
                });
#pragma warning restore 612, 618
        }
    }
}
